// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blink': string;
  'cursor': string;
  'cursorChar': string;
  'editArea': string;
  'editor': string;
  'lineNumbersArea': string;
  'sampleChar': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
